export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as ProductList } from './ProductList'
export { default as ProductEdit } from './ProductEdit'
export { default as ProductNew } from './ProductNew'